apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
spec:
  replicas: 1  # Une seule réplique pour cette application
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - name: app3
        image: arm64v8/nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app3
spec:
  selector:
    app: app3
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30003  # Choisir un port dans la plage 30000-32767
  type: NodePort